services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ztp-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  ztp:
    build:
      context: .
      dockerfile: ZTP/Dockerfile
    image: ztp-service:latest
    ports:
      - "5000:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ__HOSTNAME: rabbitmq
      IMAGE_FOLDER: /Images
    volumes:
      - ./Images:/Images

  imageprocessor:
    build:
      context: .
      dockerfile: ImageProcessorService/Dockerfile
    image: image-processor-service:latest
    ports:
      - "5001:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
      ztp:
        condition: service_started
    environment:
      RABBITMQ__HOSTNAME: rabbitmq
      IMAGE_FOLDER: /Images
    volumes:
      - ./Images:/Images  
